version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl and use pipenv to install dependencies
            python setup.py sdist
            sudo pip install pipenv
            pipenv install -r requirements.txt
            pipenv install dist/divHretention-0.1.2.tar.gz
            pipenv install pytest
      - run:
          command: |  # Run test suite
            pipenv run pytest
