version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |
            sudo python setup.py install
            sudo pip install pytest
      - run:
          command: |  # Run test suite
            pytest test/
