version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl and use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
            pipenv install pytest
      - run:
          command: |  # Run test suite
            pipenv run pytest
